--CREATED TABLE AND APPLIED DIFFERENT CONSTRAINTS

CREATE TABLE STUDENT
(STUDENT_ID INT IDENTITY,
 NAME VARCHAR(50) NOT NULL,
 MAJOR VARCHAR(50) UNIQUE,
 PRIMARY KEY(STUDENT_ID)
 )
 --DROP,ALTER STATEMENTS 
  DROP TABLE STUDENT

  ALTER TABLE STUDENT ADD
  GPA DECIMAL(3,2)

  SELECT *
  FROM STUDENT

  ALTER TABLE STUDENT DROP 
  COLUMN GPA
  
  --INSERTED VALUES TO THE TABLE
  INSERT INTO STUDENT 
  (NAME,MAJOR) VALUES ('CLARK','COMPUTER SCIENCE')
   INSERT INTO STUDENT 
  (NAME,MAJOR) VALUES ('EMILY','PHYSICS')
  INSERT INTO STUDENT 
  (NAME,MAJOR) VALUES ('DANIEL','CHEMISTRY')
  INSERT INTO STUDENT 
  (NAME,MAJOR) VALUES ('SMITH','BIOLOGY')
  INSERT INTO STUDENT
  (NAME,MAJOR) VALUES('LIZZY','ACCCOUNTING')
  INSERT INTO STUDENT VALUES
  ('SERENA','MATHEMATICS')

  --UPDATE STATEMENT
UPDATE STUDENT
SET MAJOR='BIO'
WHERE MAJOR='BIOLOGY'

UPDATE STUDENT
SET MAJOR='ENGLISH'
WHERE MAJOR='PHYSICS'

SELECT * 
FROM STUDENT

UPDATE STUDENT
SET NAME='JERRY',MAJOR='NOT SURE'
WHERE STUDENT_ID=3

UPDATE STUDENT
SET MAJOR='COMPUTER SCIENCE'
WHERE STUDENT_ID='3'OR STUDENT_ID='8'

UPDATE STUDENT
SET MAJOR='EG'
WHERE STUDENT_ID=3

UPDATE STUDENT
SET MAJOR='CHEMISTRY'
WHERE NAME='DANIEL'

--DELETE STATEMENT
DELETE FROM STUDENT
WHERE STUDENT_ID=9

--ORDER BY,GROUP BY ,WHERE,DISTINCT,IN AND AGGREGATE FUNCTIONS
SELECT NAME,MAJOR
FROM STUDENT
ORDER BY NAME,MAJOR

SELECT *
FROM STUDENT
ORDER BY STUDENT_ID DESC

--WHERE
SELECT *
FROM STUDENT
WHERE MAJOR='BIO'

SELECT *
FROM STUDENT
WHERE MAJOR IN ('COMPUTER SCIENCE','BIO') AND STUDENT_ID>=1

SELECT * 
FROM STUDENT
WHERE NAME LIKE '%H'

SELECT NAME
FROM STUDENT
WHERE NAME LIKE 'C__%'

SELECT DISTINCT(STUDENT_ID)
FROM STUDENT

SELECT NAME,MIN(STUDENT_ID) AS FIRST_ID,MAX(STUDENT_ID) AS LAST_ID
FROM STUDENT
GROUP BY NAME
ORDER BY NAME DESC

SELECT COUNT(MAJOR) AS TOTAL_MAJORS
FROM STUDENT


SELECT NAME
FROM STUDENT
WHERE NAME  IN('CLARK') OR NAME IS NOT  NULL

SELECT NAME
FROM STUDENT
WHERE NAME   NOT IN('CLARK') 

--THE END

